services:
  backup:
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-${ERPNEXT_VERSION:?No ERPNext version or tag set}}
    platform: linux/amd64
    entrypoint: ["bash", "-c"]
    command:
      - bench --site all backup
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    networks:
      - bench-network
      - mariadb-network
